version: '3.8'

services:
  web:
    build: .
    container_name: my-django-app
    command: /bin/bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=carrent.settings_dev
      - DATABASE_URL=postgres://myuser:12345@db:5432/carrental  
    depends_on:
      - db

  db:
    image: postgis/postgis
    container_name: postgresql
    environment:
      POSTGRES_DB: carrental
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
