# Generated by Django 3.2.11 on 2022-01-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('coefficient', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'currency',
            }
        ),
    ]
