# Generated by Django 3.2.11 on 2022-02-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_devise_unit'),
        ('home', '0004_agences'),
    ]

    operations = [
    ]
