# Generated by Django 3.2.11 on 2022-01-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='devise',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='devise',
            name='order_key',
            field=models.IntegerField(null=True),
        ),
    ]
