# Generated by Django 3.2.11 on 2022-02-16 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_newsletter_subscription',
            field=models.BooleanField(default=False, verbose_name='Has News Letter Subscription'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mail_verified',
            field=models.BooleanField(default=False, verbose_name='Is The Mail Verified'),
        ),
        migrations.CreateModel(
            name='MailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(auto_now_add=True, verbose_name='Subscripted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('unsubscription_date', models.DateTimeField(blank=True, null=True, verbose_name='Subscripted At')),
                ('promo_value', models.FloatField(default=0, verbose_name='Promotion price')),
                ('is_promo_used', models.BooleanField(default=False, verbose_name='Is Promotion Used')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'mail_subscription',
            },
        ),
    ]
