# Generated by Django 3.2.11 on 2022-01-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        # migrations.AlterModelTable(
        #     name='devise',
        #     table='currency',
        # ),
        migrations.AlterModelTable(
            name='userpreference',
            table='user_preference',
        ),
    ]
