# Generated by Django 3.2.11 on 2022-01-26 14:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220125_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order_key', models.IntegerField(null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'states',
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order_key', models.IntegerField(null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.state', verbose_name='State')),
            ],
            options={
                'db_table': 'delegation',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='delegation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.delegation', verbose_name='Delegation'),
        ),
    ]
