# Generated by Django 3.2.11 on 2022-02-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220216_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsubscription',
            name='subscription_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Subscripted At'),
        ),
    ]
