# Generated by Django 3.2.11 on 2022-03-19 21:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220217_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='agences',
            name='ceo_phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CEO Phone'),
        ),
        migrations.AddField(
            model_name='agences',
            name='commercial_name',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Agency Name'),
        ),
        migrations.AddField(
            model_name='agences',
            name='delegation',
            field=models.CharField(max_length=200, null=True, verbose_name='Delegation'),
        ),
        migrations.AddField(
            model_name='agences',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='agences',
            name='zipcode',
            field=models.CharField(max_length=150, null=True, verbose_name='CEO Name'),
        ),
        migrations.AlterField(
            model_name='agences',
            name='adress_agency',
            field=models.CharField(max_length=4096, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='agences',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='CEO Name'),
        ),
        migrations.AlterField(
            model_name='agences',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='agences',
            name='governorate',
            field=models.CharField(max_length=200, null=True, verbose_name='Governorate'),
        ),
    ]
