# Generated by Django 3.2.11 on 2022-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220320_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, verbose_name='Field')),
                ('acess_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rights_access',
            },
        ),
    ]
