# Generated by Django 3.2.11 on 2022-04-03 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rightsaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightsaccess',
            name='access_type',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Access Type'),
        ),
        migrations.AddField(
            model_name='rightsaccess',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
