# Generated by Django 3.2.11 on 2025-03-19 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220403_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Role Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'advisor_role',
            },
        ),
        migrations.CreateModel(
            name='AgencyAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Invited At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agences', verbose_name='Agency')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.advisorrole', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'agency_advisor',
            },
        ),
    ]
