# Generated by Django 3.2.11 on 2025-03-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_advisorrole_agencyadvisor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agencyadvisor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='agencyadvisor',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencyadvisor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='agencyadvisor',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdvisorRole',
        ),
        migrations.DeleteModel(
            name='AgencyAdvisor',
        ),
    ]
