# Generated by Django 3.2.11 on 2025-03-19 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20250319_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Role Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'advisor_role',
            },
        ),
        migrations.CreateModel(
            name='AdvisorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agences', verbose_name='Agency')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.role', verbose_name='Role')),
            ],
            options={
                'db_table': 'advisor_invitation',
            },
        ),
    ]
