# Generated by Django 3.2.11 on 2025-03-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_advisorinvitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_add_car',
            field=models.BooleanField(default=False, verbose_name='Can Add Car'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_car',
            field=models.BooleanField(default=False, verbose_name='Can Delete Car'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_update_car',
            field=models.BooleanField(default=False, verbose_name='Can Update Car'),
        ),
    ]
