# Generated by Django 3.2.11 on 2025-03-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20250319_0741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorInvitation',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
