# Generated by Django 3.2.11 on 2025-04-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20250408_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencyUserPermission',
        ),
    ]
