# Generated by Django 3.2.11 on 2025-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_agencypermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='agences',
            name='auto_approve_rental',
            field=models.BooleanField(default=False, verbose_name='Auto Approve Rentals'),
        ),
    ]
