# Generated by Django 3.2.11 on 2025-04-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20250417_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
