# Generated by Django 3.2.11 on 2025-04-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_delete_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('rental_request', 'Rental Status Update Request'), ('car_model', 'New Car Model Request'), ('agency', 'New Agency Registration')], max_length=20, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('related_object_id', models.IntegerField(verbose_name='Related Object ID')),
                ('related_object_type', models.CharField(max_length=100, verbose_name='Related Object Type')),
                ('admin_url', models.CharField(max_length=255, verbose_name='Admin URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'db_table': 'admin_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
