# Generated by Django 3.2.11 on 2025-04-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_adminnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
