# Generated by Django 3.2.11 on 2025-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_delete_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('rental', 'Rental Request'), ('car_model', 'Car Model Request'), ('agency', 'Agency Registration')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('target_url', models.CharField(max_length=255)),
                ('reference_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'admin_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
