# Generated by Django 3.2.11 on 2025-04-25 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('fuel_policy', models.CharField(max_length=255)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_license_age', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('with_driver', models.BooleanField(default=False, verbose_name='With Driver')),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Driver Name')),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Driver Phone')),
                ('driver_license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Driver License Number')),
                ('driver_experience_years', models.IntegerField(blank=True, null=True, verbose_name='Driver Experience (Years)')),
                ('driver_languages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Driver Languages')),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.agences')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('img_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('img_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car_brand',
            },
        ),
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gear_type',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transmission',
            },
        ),
        migrations.CreateModel(
            name='CarUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_periods', to='cars.agencycar')),
            ],
            options={
                'verbose_name': 'Car Unavailability',
                'verbose_name_plural': 'Car Unavailability',
                'db_table': 'car_unavailability',
            },
        ),
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('full', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cars.agencycar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Reservation',
                'verbose_name_plural': 'Car Reservations',
                'db_table': 'car_reservation',
            },
        ),
        migrations.CreateModel(
            name='CarModelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Model Request',
                'verbose_name_plural': 'Car Model Requests',
                'db_table': 'car_model_request',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model Description')),
                ('img_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('img_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('air_conditioner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Air Conditioner')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('cylinder', models.FloatField(blank=True, null=True, verbose_name='Engine Cylinder')),
                ('horse_power', models.FloatField(blank=True, null=True, verbose_name='Horse Power')),
                ('doors_nbr', models.IntegerField(blank=True, null=True, verbose_name='Door Number')),
                ('place_nbr', models.IntegerField(blank=True, null=True, verbose_name='Place Number')),
                ('energy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Energy')),
                ('extra_urban_consumption', models.FloatField(blank=True, null=True, verbose_name='Extra Urban Consumption')),
                ('urban_consumption', models.FloatField(blank=True, null=True, verbose_name='Urban Consumption')),
                ('mixte_consumption', models.FloatField(blank=True, null=True, verbose_name='Mixte Consumption')),
                ('gear_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gear Type')),
                ('gear_nbr', models.IntegerField(blank=True, null=True, verbose_name='Gear Number')),
                ('transmission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transmission')),
                ('max_speed', models.IntegerField(blank=True, null=True, verbose_name='Max Speed')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Car Length')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Car Width')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Car Height')),
                ('trunk_volume', models.IntegerField(blank=True, null=True, verbose_name='Trunk Volume')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('order_key', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand', verbose_name='Brand')),
            ],
            options={
                'db_table': 'car_model',
            },
        ),
        migrations.AddField(
            model_name='agencycar',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand'),
        ),
        migrations.AddField(
            model_name='agencycar',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel'),
        ),
        migrations.AddField(
            model_name='agencycar',
            name='gear_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.geartype', verbose_name='Gear Type'),
        ),
    ]
