# Generated by Django 3.2.11 on 2022-02-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('img_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('img_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car_brand',
            },
        ),
    ]
