# Generated by Django 3.2.11 on 2025-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencycar',
            name='minimum_rental_days',
            field=models.IntegerField(default=1, verbose_name='Minimum Rental Days'),
        ),
    ]
