# Generated by Django 3.2.11 on 2022-02-05 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_brand_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gear_type',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transmission',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model Description')),
                ('img_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('img_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('air_conditioner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Air Conditioner')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('cylinder', models.FloatField(blank=True, null=True, verbose_name='Engine Cylinder')),
                ('horse_power', models.FloatField(blank=True, null=True, verbose_name='Horse Power')),
                ('doors_nbr', models.IntegerField(blank=True, null=True, verbose_name='Door Number')),
                ('place_nbr', models.IntegerField(blank=True, null=True, verbose_name='Place Number')),
                ('energy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Energy')),
                ('extra_urban_consumption', models.FloatField(blank=True, null=True, verbose_name='Extra Urban Consumption')),
                ('urban_consumption', models.FloatField(blank=True, null=True, verbose_name='Urban Consumption')),
                ('mixte_consumption', models.FloatField(blank=True, null=True, verbose_name='Mixte Consumption')),
                ('gear_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gear Type')),
                ('gear_nbr', models.IntegerField(blank=True, null=True, verbose_name='Gear Number')),
                ('transmission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transmission')),
                ('max_speed', models.IntegerField(blank=True, null=True, verbose_name='Max Speed')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Car Length')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Car Width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Car Height')),
                ('trunk_volume', models.IntegerField(blank=True, null=True, verbose_name='Trunk Volume')),
                ('order_key', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand', verbose_name='Brand')),
            ],
            options={
                'db_table': 'car_model',
            },
        ),
    ]
