# Generated by Django 3.2.11 on 2025-04-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_add_driver_fields'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agencycar',
            table='agency_car',
        ),
    ]
