# Generated by Django 3.2.11 on 2025-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_agencycar_minimum_rental_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencycar',
            name='for_transfer',
            field=models.BooleanField(default=False, verbose_name='Available for Transfer'),
        ),
        migrations.AddField(
            model_name='agencycar',
            name='max_luggage_pieces',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Luggage Pieces'),
        ),
        migrations.AddField(
            model_name='agencycar',
            name='max_luggage_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Maximum Luggage Weight (kg)'),
        ),
        migrations.AddField(
            model_name='agencycar',
            name='max_passengers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Passengers'),
        ),
        migrations.AddField(
            model_name='agencycar',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Hour'),
        ),
        migrations.AddField(
            model_name='agencycar',
            name='price_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Kilometer'),
        ),
    ]
