# Generated by Django 3.2.11 on 2025-05-13 09:45

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_auto_20250513_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateTimeField(verbose_name='Pickup Date and Time')),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Pickup Location')),
                ('pickup_address', models.CharField(max_length=255, verbose_name='Pickup Address')),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Dropoff Location')),
                ('dropoff_address', models.CharField(max_length=255, verbose_name='Dropoff Address')),
                ('pricing_type', models.CharField(choices=[('distance', 'By Distance'), ('hourly', 'By Hour')], default='distance', max_length=20)),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance (km)')),
                ('duration_hours', models.FloatField(blank=True, null=True, verbose_name='Duration (hours)')),
                ('passengers_count', models.PositiveIntegerField(verbose_name='Number of Passengers')),
                ('luggage_pieces', models.PositiveIntegerField(default=0, verbose_name='Number of Luggage Pieces')),
                ('luggage_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Luggage Weight (kg)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_bookings', to='cars.agencycar')),
            ],
            options={
                'verbose_name': 'Transfer Booking',
                'verbose_name_plural': 'Transfer Bookings',
                'db_table': 'transfer_booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
