# Generated by Django 3.2.11 on 2025-05-13 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_transferbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbooking',
            name='dropoff_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dropoff Address'),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='dropoff_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Dropoff Location'),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pickup Address'),
        ),
        migrations.AlterField(
            model_name='transferbooking',
            name='pickup_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Pickup Location'),
        ),
    ]
