# Generated by Django 3.2.11 on 2025-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20220206_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='img_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
