# Generated by Django 3.2.11 on 2025-03-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20250315_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('fuel_policy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fuel Policy')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Security Deposit')),
                ('minimum_license', models.CharField(blank=True, max_length=255, null=True, verbose_name='Minimum License')),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Day')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand', verbose_name='Brand')),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Car Model')),
            ],
        ),
    ]
