# Generated by Django 3.2.11 on 2025-03-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
