# Generated by Django 3.2.11 on 2025-03-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220403_1527'),
        ('cars', '0008_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_policy', models.CharField(choices=[('full_to_full', 'Full to Full'), ('full_to_empty', 'Full to Empty'), ('same_to_same', 'Same to Same')], max_length=20, verbose_name='Fuel Policy')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Security Deposit')),
                ('min_license_age', models.IntegerField(verbose_name='Minimum License Age')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Day')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('img_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('img_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agences', verbose_name='Agency')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Car Model')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
