# Generated by Django 3.2.11 on 2025-03-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_agencycar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencycar',
            name='location',
        ),
    ]
