# Generated by Django 3.2.11 on 2025-03-16 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_remove_agencycar_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencycar',
            name='gear_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.geartype', verbose_name='Gear Type'),
        ),
    ]
