# Generated by Django 3.2.11 on 2025-03-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_agencycar_gear_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencycar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
