# Generated by Django 3.2.11 on 2025-03-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20250323_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarModelRequest',
        ),
    ]
