# Generated by Django 3.2.11 on 2025-04-01 07:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_carmodelrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencycar',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
