# Generated by Django 3.2.11 on 2025-04-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_agencycar_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencycar',
            name='location',
        ),
    ]
