# Generated by Django 3.2.11 on 2025-04-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_remove_agencycar_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencycar',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
