# Generated by Django 3.2.11 on 2025-04-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_agencycar_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencycar',
            name='is_featured',
        ),
    ]
