# Generated by Django 3.2.11 on 2025-04-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_carreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarReservation',
        ),
    ]
