# Generated by Django 3.2.11 on 2025-04-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_carreservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencycar',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='agencycar',
            table='agency_car',
        ),
    ]
