# Generated by Django 3.2.11 on 2025-04-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_auto_20250411_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencycar',
            options={},
        ),
        migrations.AlterModelTable(
            name='agencycar',
            table=None,
        ),
    ]
