# Generated by Django 3.2.11 on 2025-04-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_auto_20250411_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order_key', 'name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['brand__name', 'name'], 'verbose_name': 'Car Model', 'verbose_name_plural': 'Car Models'},
        ),
        migrations.AlterModelOptions(
            name='carmodelrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Car Model Request', 'verbose_name_plural': 'Car Model Requests'},
        ),
        migrations.AlterModelOptions(
            name='geartype',
            options={'ordering': ['order_key', 'name'], 'verbose_name': 'Gear Type', 'verbose_name_plural': 'Gear Types'},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'ordering': ['order_key', 'name'], 'verbose_name': 'Transmission', 'verbose_name_plural': 'Transmissions'},
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
    ]
