# Generated by Django 3.2.11 on 2025-04-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0029_auto_20250411_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carmodelrequest',
            options={'verbose_name': 'Car Model Request', 'verbose_name_plural': 'Car Model Requests'},
        ),
        migrations.AlterModelOptions(
            name='geartype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={},
        ),
        migrations.AlterModelTable(
            name='brand',
            table='car_brand',
        ),
    ]
