# Generated by Django 3.2.11 on 2025-04-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_rentalstatuschange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalStatusChange',
        ),
    ]
