# Generated by Django 3.2.11 on 2025-04-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_rentalstatuschange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalStatusChange',
        ),
    ]
